import { useState } from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { fetchWeatherData } from '@/lib/api'
import WeatherAcrossDates from '@/components/WeatherAcrossDates'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isFetching, setIsFetching] = useState(false);
  const [weatherData, setWeatherData] = useState(null);

  const handleFetch = async() => {
    setIsFetching(true);
    return fetchWeatherData()
      .then(data => setWeatherData(data))
      .catch(error => console.log(error))
      .finally(() => setIsFetching(false))
  }

  const renderWeatherData = () => {
    if (isFetching) return <div>Loading Data</div>
    return (<div className=''>
      <WeatherAcrossDates data={weatherData} />
      <button onClick={handleFetch}>Fetch Weather</button>
    </div>)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        {renderWeatherData()}
      </main>
    </>
  )
}
