import { useEffect, useState } from 'react'
import Head from 'next/head'
import { Inter } from 'next/font/google'
import { fetchWeatherData } from '@/lib/api'
import WeatherAcrossDates from '@/components/WeatherAcrossDates'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isFetching, setIsFetching] = useState(false);
  const [weatherData, setWeatherData] = useState(null);
  const [weatherConfig, setWeatherConfig] = useState({
    datetime: `${dayjs().utcOffset(-6, true).format(`YYYY-MM-DDThh:mm:ssZ`)}P5D:PT1H`,
    coordinates: [29.749907, -95.358421],
    parameters: ["t_2m:C", "t_min_2m_24h:C", "t_max_2m_24h:C", "uv:idx", "sunrise:sql", "sunset:sql", "weather_symbol_1h:idx"]
  });
  const [configView, toggleConfigView] = useState(false);

  useEffect(() => {
    handleFetch();
  }, [])

  const handleFetch = async() => {
    setIsFetching(true);
    return fetchWeatherData()
      .then(data => setWeatherData(data))
      .catch(error => console.log(error))
      .finally(() => setIsFetching(false))
  }

  const renderWeatherData = () => {
    return (<div className=''>
      {isFetching ? <div>Loading Data</div> : <WeatherAcrossDates data={weatherData} />}
      <button onClick={() => toggleConfigView(true)} className="fetch-button">Open Config</button>
      <div className='weather-fetch-config' style={{ right: configView ? "0px" : "-400px" }}>
        <button onClick={handleFetch}>Fetch</button>
        <button onClick={() => toggleConfigView(false)}>Close</button>
      </div>
    </div>)
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className} weather-main`}>
        {renderWeatherData()}
      </main>
    </>
  )
}
